name: customrombay.org
description: A place to find all custom ROMs available for your device.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  args: ^2.3.1
  path: ^1.8.0
  serve: ^3.0.1
  yaml: ^3.1.1
  staurolite:
    git: 
      url: https://github.com/piotrzpl/staurolite

